### ISSUE TITLE
Blocks the application if graylog server is not reachable

### ISSUE THREAD

**Issue by mitulmakadia** [jjchiw/gelf4net#39]
While working on server migration, we accidentally forget to allow graylog server in firewall. The log statement was pausing the code execution due to unreachable Graylog server upto 20 seconds before stepping forward.

This poses a serious risk to production environment. Is there anyway we can have log statements are executed asynchronously?

**Comment by jjchiw** [comment]
I'll look into that gelf4net should not block the execution.

About the async appender I thought it was merged in master it's still in a separate branch https://github.com/jjchiw/gelf4net/tree/async-appenders

I'll merge them during the weekend and look into the app blocking

**Comment by mitulmakadia** [comment]
Thanks jjchiw! Looking forward to it. This has been proving helpful to us so far.

**Comment by jjchiw** [comment]
Hi, I remembered why I didn't add the asyncappenders was because we didn't finish the testing https://github.com/jjchiw/gelf4net/pull/27 I'll merge it since wjdavid5 said that it's being used in production....

About the 20 seconds delay, I added a `Stopwatch` in https://github.com/jjchiw/gelf4net/tree/master/examples/SimpleConsoleApplication and I can not reproduce the delay.

I uploaded a new version with the asyncappenders https://www.nuget.org/packages/Gelf4Net/2.0.3.16

**Comment by lalit-bhatt** [comment]
Hi jjchiw,

I tried using HttpAppender from the new version (2.0.3.16) but faced the issue where application got blocked and took around 20 seconds to respond. However, AsyncUdpAppender worked well. Not sure about the issue with HttpAppender.

Thanks

**Comment by jjchiw** [comment]
About the application that got blocked, I can not reproduce it, in the example https://github.com/jjchiw/gelf4net/tree/master/examples/SimpleConsoleApplication where I use the three appender `UdpAppender`, `AsyncUdpAppender`, `HttpAppender` and I have graylog turned off, the applications do not hangs....

I don't know if I can look into that.... 

Great you got it working with the AsyncUdpAppender.
