### ISSUE TITLE
GELF HttpAppender caused a memory leak when GrayLog server was down

### ISSUE THREAD

**Issue by rdadbhawala-cmspl** [jjchiw/gelf4net#42]
Started using the GELF HTTP appender to submit logs directly to the GrayLog server from the service. When the GrayLog server had a prolonged downtime, it led to a memory leak in our service. Stopping the appender resolved the issue for us.

**Comment by jjchiw** [comment]
Hi, which nuget package are you using 

- [`Gelf4Net`](https://www.nuget.org/packages/Gelf4Net/)
- [`Gelf4Net.HttpAppender`](https://www.nuget.org/packages/Gelf4Net.HttpAppender/)

Since the implementation is different in `Gelf4Net` uses `WebClient` because it targets the framework 4.0 and `Gelf4Net.HttpAppender` uses `HttpClient` which target 4.5

I'm going to update `Gelf4Net` to framework 4.5 and it'll use `HttpClient`....

If you were using `Gelf4Net` maybe with the update it'll solve the issues if you were using `Gelf4Net.HttpAppender` I'll have to make some tests :) 

I pushed a new nuget package.

**Comment by rdadbhawala-cmspl** [comment]
Gelf4Net.2.0.3.14
I will not be able to test it immediately. We are waiting for our IT/DC team to setup a GrayLog cluster. Will take up updates after the infrastructure is in place.
Thanks for responding.

**Comment by jjchiw** [comment]
It took some time, but I was able to reproduce it 5 years later :/

https://github.com/jjchiw/gelf4net/issues/75
